---
# SPDX-FileCopyrightText: 2025 The python_openobserve authors
# SPDX-License-Identifier: GPL-3.0-or-later
name: pytest-poetry

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.12", "3.14"]

    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.openobserve
      ANSIBLE_SUITE: default-full-python

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # tag=v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # tag=v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache the virtualenv
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # tag=v4.3.0
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt
            ./.venv
          key: ${{ runner.os }}-pyo2-${{ steps.get-date.outputs.date }}

      - name: Install ansible dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint jmespath
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          git clone https://github.com/juju4/ansible-openobserve/ $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          { echo '[defaults]'; echo 'callback_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Install OpenObserve
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -v molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        continue-on-error: true

      - name: Set .env for online tests
        run: |
          set -x
          cat > .env <<EOF
          OPENOBSERVE_URL = "http://localhost:5080"
          OPENOBSERVE_USER = "root@example.com"
          OPENOBSERVE_PASS = "root@example.com"
          EOF
          cat .env

      - name: Install poetry
        run: |
          python -m pip install poetry==2.2.1

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          python -m poetry install --all-extras

      - name: Test with pytest - offline
        run: |
          python -m poetry run python -m pytest -sxv tests/test_*offline.py --doctest-modules --junitxml=junit/test-${{ matrix.python-version }}-results.xml --cov=com --cov-report=xml --cov-report=html --memray

      - name: Test with pytest  - online
        run: |
          [ -f .env ] && python -m poetry run python -mpytest tests/test_openobserve_api.py --doctest-modules --junitxml=junit/test-${{ matrix.python-version }}-results.xml --cov=com --cov-report=xml --cov-report=html --memray
        if: ${{ always() }}
        continue-on-error: true
